# Ignore "whitelist" - upstream uses this non compliant terminology.
ignore_files:
 - lib/charms/nginx_ingress_integrator/v0/ingress.py
rules:
  # Ignore "master" - the database relation event received from the library
  # uses this terminology.
  - name: master
