{
 "title": "Discourse Service Health",
 "tags": [ "service-health" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "LATENCY",
   "type": "timeseries",
   "description": "99% of HTTP requests were completed in the time displayed on the panel or less.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(discourse_http_duration_seconds{quantile=\"0.99\",action=\"latest\",controller=\"list\"})",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "description": "Total of errors (status code 4* or 5*)",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(discourse_http_requests{status=~\"^[45].*\"}[5m])) by (status, job)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "description": "Number of active requests",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(discourse_active_app_reqs{}) by (job)",
     "legendFormat": "Active requests"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "description": "V8 used memory and number of active threads",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(discourse_v8_used_heap_size)",
     "legendFormat": "Memory"
    },
    { "expr": "sum(discourse_thread_count)", "legendFormat": "Active threads" }
   ]
  }
 ]
}