#!/bin/bash
#
# cleanup_post_build
#
# This does any post-build steps that need to be run and removes anything that
# should not exist in the image. Note that removals here do not save space, they
# simply remove the file references from the running image.

apt-get autoremove
apt-get clean

rm -rf /srv/build_scripts
