#!/bin/bash
#
# get_app_dependencies
#
# Installs application-specific dependencies for this image.
 
apt-get install -y brotli \
                   gifsicle \
                   git \
                   imagemagick \
                   jhead \
                   jpegoptim \
                   libjpeg-turbo-progs \
                   libpq-dev \
                   libssl-dev \
                   libxml2-dev \
                   libxslt1-dev \
                   libz-dev \
                   uglifyjs.terser \
                   node-uglify \
                   optipng \
                   pngquant \
                   postgresql-client \
                   postgresql-client-common \
                   redis-tools \
                   ruby2.7 \
                   ruby2.7-dev \
                   zlib1g-dev

# Older versions of the uglifyjs.terser package install a uglifyjs.terser
# command but not the terser command, terser command exists in $PATH is
# vital to trigger js assets compression using node. Manually create the
# terser command if it does not exist. Please remove this line if the
# base image is >= 22.04. Also, please consider removing the node-uglify
# when upgrading to discourse >= 2.8.0, since the node-uglify is not
# required to trigger node js assets compression, only terser will do fine.
which terser || ln -s $(which uglifyjs.terser) /usr/local/bin/terser