#!/bin/bash
#
# setup_base_layer 
#
# This sets up the base image with common tools and packages that are needed for
# most images.
#
# Update our packages.
apt-get update

# Set our timezone to UTC.
ln -s /usr/share/zoneinfo/UTC /etc/localtime

# Get our base packages.
apt-get install -y gettext-base tzdata ubuntu-dev-tools git

# Create our application group.
/usr/sbin/addgroup --gid ${CONTAINER_APP_GID} ${CONTAINER_APP_GROUP}

# Create our application user - this also creates our app root. 
/usr/sbin/adduser --uid ${CONTAINER_APP_UID} --home ${CONTAINER_APP_ROOT} --gid ${CONTAINER_APP_GID} --system ${CONTAINER_APP_USERNAME}
