#!/bin/bash

# pod_start
#
# This script is the primary entrypoint for the pod. It should start up the
# primary service and output log data to stdout. It should also exit when the
# application exits in order for the pod to terminate properly.

# Steps:
#  1) Launch application - should not exit until application exits.
#  2) Do any pod-exit cleanup.

APP_EXIT="notrun"

echo "Launching ${CONTAINER_APP_NAME}"
/srv/scripts/app_launch
APP_EXIT=$?
echo "${CONTAINER_APP_NAME} exited with code ${APP_EXIT}"

# Run pod_exit with either the pod_setup exit code, or the app_launch exit code
# as the first argument.
/srv/scripts/pod_exit "$SETUP_EXIT" "$APP_EXIT"
