#!/bin/bash

# pod_exit
#
# Run when a pod is terminating, assuming it's terminating normally. This gives
# us a chance to do any api-calls, notifications or last-minute cleanup prior to
# pod exit.
 
SETUP_EXITCODE=$1
APP_EXITCODE=$2

echo "Setup exited with exit code ${SETUP_EXITCODE}"
echo "App exited with exit code ${APP_EXITCODE}"

exit ${APP_EXITCODE} 
