name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs.yaml@temporarly-disable-link-checker
    secrets: inherit
