name: Publish to edge

on:
  push:
    branches:
    - main
    - track/*

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@58ae6614a3b143d4e57eff0fd1770e97d8c30fab # v1.0.1
    permissions:
      actions: read
      contents: write
      packages: write
    with:
      channel: latest/edge
      integration-workflow-name: integration_test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
