name: Publish to edge

on:
  push:
    branches:
    - main
    - track/*

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@14b1cf49d48b9d5b96192d9bca2890c98b7295cf # v1.0.2
    permissions:
      actions: read
      contents: write
      packages: write
    with:
      channel: latest/edge
      integration-workflow-name: integration_test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
