name: Publish to edge

on:
  push:
    branches:
    - main
    - track/*

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@v0.0.1-alpha.6
    permissions:
      actions: read
      contents: write
      packages: write
    with:
      channel: latest/edge
      integration-workflow-name: integration_test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
