name: Tests

on:
  pull_request:

jobs:
  draft-publish-docs:
    name: Draft publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Publish documentation
        uses: canonical/discourse-gatekeeper@investigate-nothing-to-commit-bug
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
