name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@python-version
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    with:
      with-uv: true
      self-hosted-runner: true
      self-hosted-runner-label: "edge"

