name: Publish to edge

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - track/**

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/test_and_publish_charm.yaml@main
    secrets: inherit
    with:
     integration-test-extra-arguments: >
      --s3-url http://172.17.0.1:4566
      -m "not (requires_secrets)"
     integration-test-pre-run-script: localstack-installation.sh
     trivy-image-config: "trivy.yaml"
